// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void CategoriaMotivo() {
    driver.Navigate().GoToUrl("https://danieljairton.github.io/Projetos%20SENAI/Almoxarifado/Almoxarifado-main/index.html");
    driver.Manage().Window.Size = new System.Drawing.Size(945, 1012);
    driver.FindElement(By.Id("categoriaMotivo")).Click();
    {
      var dropdown = driver.FindElement(By.Id("categoriaMotivo"));
      dropdown.FindElement(By.XPath("//option[. = 'Gestão']")).Click();
    }
    driver.FindElement(By.Id("categoriaMotivo")).Click();
    {
      var dropdown = driver.FindElement(By.Id("categoriaMotivo"));
      dropdown.FindElement(By.XPath("//option[. = 'Cliente']")).Click();
    }
    driver.FindElement(By.Id("Motivo")).Click();
    {
      var dropdown = driver.FindElement(By.Id("Motivo"));
      dropdown.FindElement(By.XPath("//option[. = 'Quebra de máquinas']")).Click();
    }
    driver.FindElement(By.Id("categoriaMotivo")).Click();
    {
      var dropdown = driver.FindElement(By.Id("categoriaMotivo"));
      dropdown.FindElement(By.XPath("//option[. = 'RP']")).Click();
    }
    driver.FindElement(By.Id("Motivo")).Click();
    driver.FindElement(By.Id("Motivo")).Click();
    driver.FindElement(By.Id("categoriaMotivo")).Click();
    {
      var dropdown = driver.FindElement(By.Id("categoriaMotivo"));
      dropdown.FindElement(By.XPath("//option[. = 'Gestão']")).Click();
    }
    driver.FindElement(By.Id("Motivo")).Click();
    {
      var dropdown = driver.FindElement(By.Id("Motivo"));
      dropdown.FindElement(By.XPath("//option[. = 'Planejamento']")).Click();
    }
  }
}
