// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Statusdoestoque() {
    driver.Navigate().GoToUrl("https://danieljairton.github.io/Projetos%20SENAI/Almoxarifado/Almoxarifado-main/index.html");
    driver.Manage().Window.Size = new System.Drawing.Size(945, 1012);
    driver.FindElement(By.CssSelector(".grupoProduto")).Click();
    driver.FindElement(By.Id("CodigoProduto")).Click();
    driver.FindElement(By.Id("CodigoProduto")).SendKeys("1");
    driver.FindElement(By.CssSelector(".grupoProdutoDescricao > span")).Click();
    driver.FindElement(By.Id("CodigoProduto")).Click();
    driver.FindElement(By.Id("CodigoProduto")).SendKeys("2");
    driver.FindElement(By.CssSelector(".grupoProduto")).Click();
    driver.FindElement(By.Id("CodigoProduto")).Click();
    driver.FindElement(By.Id("CodigoProduto")).Click();
    driver.FindElement(By.Id("CodigoProduto")).SendKeys("3");
  }
}
